### ISSUE TITLE
Remove `wait-for` command in favor of health checks

### ISSUE THREAD

**Issue by moseshll** [hathitrust/otis#219]

**Comment by moseshll** [comment]
Resolved as part of DEV-1241

**Comment by Ronster2018** [comment]
While updating the deploy actions, there was also a need to remove `bin/wait-for`. With this effort, I added the following snippets to the `dockerfile` that has been used previously to replace `bin/wait-for`.

```yaml
x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

  system-test:
    ...
    depends_on:
      mariadb-test: *healthy
      chrome-server: *healthy

  mariadb-test:
    ...
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]

  chrome-server:
    ...
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
```
